import { access, mkdir, readFile, readdir, unlink, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

let key = process.env.ELEVENLABS_API_KEY;
if (!key) {
  const src = await readFile(
    new URL('../../lib/core/audio/story_sentence_voice.dart', import.meta.url),
    'utf8',
  );
  key = src.match(/sk_[A-Za-z0-9]+/)?.[0];
}
if (!key) {
  console.error('Missing ELEVENLABS_API_KEY');
  process.exit(1);
}

const supabaseUrl = 'https://sqvbbsqmwktxuapwivnk.supabase.co';
const supabaseKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxdmJic3Ftd2t0eHVhcHdpdm5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkxMzY3NTAsImV4cCI6MjEwNDcxMjc1MH0.w4rUqvb8eXZ77x6nHiDX004jPdctHX7CJLVdVVEaOnI';

const staticPhrases = [
  'أهلاً بك',
  'Glow',
  'رحلة الأبطال',
  'ابدأ الرحلة',
  'أوسمتي',
  'نسخ الكود',
  'تسجيل الخروج',
  'خروج',
  'مغلق. أكمل العالم السابق',
  'عمل رائع يا بطل',
  'لقد أنهيت مشاهد القصة بنجاح',
  'الآن حان وقت التحدي لإثبات مهارتك وجمع النقاط',
  'اختبر نفسك',
  'أحسنت يا بطل',
  'إرسال الإجابة',
  'رؤية أوسمتي',
  'العودة للرئيسية',
  'متابعة المشهد',
  'إنهاء القصة والتحدي',
  'السابق',
  'التالي',
  'إعادة',
  'تشغيل',
  'إيقاف',
  'كتم الصوت',
  'تشغيل الصوت',
  'رجوع',
  'انطلق',
  'إجابة خاطئة، حاول مرة أخرى',
  'إجابة صحيحة، أحسنت',
];

async function supabaseRows(table, select) {
  const response = await fetch(
    `${supabaseUrl}/rest/v1/${table}?select=${encodeURIComponent(select)}`,
    {
      headers: {
        apikey: supabaseKey,
        Authorization: `Bearer ${supabaseKey}`,
      },
    },
  );
  if (!response.ok) {
    console.error('supabase', table, response.status, await response.text());
    return [];
  }
  return response.json();
}

function fileId(phrase) {
  return createHash('sha1').update(phrase).digest('hex').slice(0, 12);
}

function pickVoice() {
  // Lily: a soft young voice the free plan can synthesize.
  const voiceId = 'pFZP5JQG7iQjIQuC4Bku';
  console.log('voice Lily', voiceId);
  return voiceId;
}

async function speak(voiceId, phrase) {
  const response = await fetch(
    `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}?output_format=mp3_44100_128`,
    {
      method: 'POST',
      headers: {
        'xi-api-key': key,
        'Content-Type': 'application/json',
        Accept: 'audio/mpeg',
      },
      body: JSON.stringify({
        text: phrase,
        model_id: 'eleven_multilingual_v2',
        voice_settings: {
          stability: 0.8,
          similarity_boost: 0.62,
          style: 0,
          use_speaker_boost: false,
        },
        speed: 0.84,
      }),
    },
  );
  if (response.status === 429 || response.status >= 500) {
    return null;
  }
  if (!response.ok) {
    console.error('tts', response.status, (await response.text()).slice(0, 300));
    process.exit(1);
  }
  return Buffer.from(await response.arrayBuffer());
}

const worlds = await supabaseRows('worlds', 'title');
const missions = await supabaseRows('missions', 'title');
const questions = await supabaseRows('questions', 'options');
const phrases = new Set(staticPhrases);
for (const row of worlds) if (row.title) phrases.add(String(row.title).trim());
for (const row of missions) if (row.title) phrases.add(String(row.title).trim());
for (const row of questions) {
  const options = Array.isArray(row.options) ? row.options : [];
  for (const option of options) {
    const text = String(option).trim();
    if (text) phrases.add(text);
  }
}

const unique = [...phrases];
console.log('phrases', unique.length, 'worlds', worlds.length, 'missions', missions.length);

const voiceId = await pickVoice();
const outDir = new URL('../../assets/voice/child/', import.meta.url);
await mkdir(outDir, { recursive: true });

const clips = {};
for (const phrase of unique) {
  const id = fileId(phrase);
  const fileUrl = new URL(`${id}.mp3`, outDir);
  try {
    await access(fileUrl);
    clips[phrase] = `voice/child/${id}.mp3`;
    console.log('kept', id, phrase);
    continue;
  } catch {
    // Generate only clips that are not already in the app.
  }
  let bytes = null;
  for (let attempt = 1; attempt <= 4 && !bytes; attempt += 1) {
    bytes = await speak(voiceId, phrase);
    if (!bytes) await new Promise((resolve) => setTimeout(resolve, 1200 * attempt));
  }
  if (!bytes) {
    console.error('tts gave up', phrase);
    process.exit(1);
  }
  await writeFile(new URL(`${id}.mp3`, outDir), bytes);
  clips[phrase] = `voice/child/${id}.mp3`;
  console.log('saved', id, phrase);
}

const dart = `// Generated by tools/voice/generate_child_buttons.mjs. Same ElevenLabs voice for every clip.
const childButtonClips = <String, String>{
${Object.entries(clips)
  .map(([phrase, asset]) => `  ${JSON.stringify(phrase)}: ${JSON.stringify(asset)},`)
  .join('\n')}
};
`;
await writeFile(
  new URL('../../lib/core/audio/child_button_clips.dart', import.meta.url),
  dart,
);
const kept = new Set(Object.values(clips).map((asset) => asset.split('/').pop()));
for (const name of await readdir(outDir).catch(() => [])) {
  if (name.endsWith('.mp3') && !kept.has(name)) await unlink(new URL(name, outDir));
}
console.log('done', unique.length);
